# Generated by Django 4.0.6 on 2022-12-20 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recencement', '0003_data_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, unique=True)),
                ('lastname', models.CharField(max_length=200, unique=True)),
                ('is_fidele', models.IntegerField(choices=[(0, 'pas fidele'), (1, 'fidele')], default=0)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recencement.eglise')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, unique=True)),
                ('lastname', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('is_maried', models.IntegerField(choices=[(0, 'Marié'), (1, 'Célibataire'), (2, 'Veuve/veuf')], default=0)),
                ('is_baptised', models.IntegerField(choices=[(0, 'Pas encore baptisé'), (1, 'baptisé')], default=0)),
                ('situation_familiale', models.IntegerField(choices=[(0, 'Père'), (1, 'Mère'), (2, 'Fils/Fille'), (3, 'Adopté (Taiza)'), (4, 'MPANAMPY')], default=0)),
                ('feu', models.IntegerField(choices=[(0, 'mort'), (1, 'vivant')], default=1)),
                ('sexe', models.IntegerField(choices=[(0, 'Féminin'), (1, 'Masculin')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('baptheme', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recencement.baptheme')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recencement.eglise')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recencement.famille')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='baptheme',
            name='eglise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recencement.eglise'),
        ),
    ]
