# Generated by Django 4.0.6 on 2022-12-20 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0005_alter_baptheme_created_on_alter_eglise_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 58, 58, 905203)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 58, 58, 905203)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 58, 58, 905203)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='famille',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 58, 58, 905203)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
    ]
