# Generated by Django 4.0.6 on 2023-03-03 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0007_personne_image_url_alter_baptheme_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 16, 41, 566220)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 16, 41, 566220)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 16, 41, 566220)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 16, 41, 566220)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='situation_familiale',
            field=models.IntegerField(choices=[(0, 'Père'), (1, 'Mère'), (2, 'Fils/Fille'), (3, 'Adopté (Taiza)'), (4, 'MPANAMPY')], default=0, null=True),
        ),
    ]
