# Generated by Django 4.0.6 on 2023-03-03 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0008_alter_baptheme_created_on_alter_eglise_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 20, 37, 40171)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 20, 37, 40171)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 20, 37, 40171)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 20, 37, 40171)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='feu',
            field=models.IntegerField(choices=[(0, 'mort'), (1, 'vivant')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_baptised',
            field=models.IntegerField(choices=[(0, 'Pas encore baptisé'), (1, 'baptisé')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_maried',
            field=models.IntegerField(choices=[(0, 'Marié'), (1, 'Célibataire'), (2, 'Veuve/veuf')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.IntegerField(choices=[(0, 'Féminin'), (1, 'Masculin')], default=0, null=True),
        ),
    ]
