# Generated by Django 4.0.6 on 2023-03-03 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0009_alter_baptheme_created_on_alter_eglise_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='is_fidele',
            field=models.IntegerField(choices=[(0, 'pas fidele'), (1, 'fidele')], default=0),
        ),
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 36, 54, 362852)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 36, 54, 362852)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 36, 54, 362852)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 36, 54, 362852)),
        ),
    ]
