# Generated by Django 4.0.6 on 2023-03-03 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0010_personne_is_fidele_alter_baptheme_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 50, 42, 918623)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 50, 42, 918623)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 50, 42, 918623)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='is_fidele',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 50, 42, 918623)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='feu',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_baptised',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_fidele',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_maried',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='situation_familiale',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
