# Generated by Django 4.0.6 on 2023-03-03 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0011_alter_baptheme_created_on_alter_eglise_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 59, 15, 106468)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 59, 15, 106468)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 59, 15, 106468)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='is_fidele',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 59, 15, 106468)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='feu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_baptised',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_fidele',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_maried',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='situation_familiale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
