# Generated by Django 4.0.6 on 2023-03-03 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0012_alter_baptheme_created_on_alter_eglise_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 6, 50, 759462)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 6, 50, 759462)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 6, 50, 759462)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='baptheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recencement.baptheme'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 6, 50, 759462)),
        ),
    ]
