# Generated by Django 4.0.6 on 2023-03-21 14:50

import datetime
from django.db import migrations, models
import recencement.models


class Migration(migrations.Migration):

    dependencies = [
        ('recencement', '0017_alter_baptheme_created_on_alter_eglise_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=recencement.models.famille_upload_to),
        ),
        migrations.AlterField(
            model_name='baptheme',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 50, 38, 993906)),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 50, 38, 993906)),
        ),
        migrations.AlterField(
            model_name='famille',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 50, 38, 993906)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 50, 38, 993906)),
        ),
    ]
